name: v3 Sync Tenant Repo to Main Repo
 
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
 
      - name: Clone scripts branch
        run: |
          mkdir scripts_folder
          git clone --branch scripts --single-branch https://github.com/Swa-DevOps/aem-guides-wknd.git scripts_folder/
          pwd
          mv scripts_folder/* .
          pwd
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=swa-devops_aem-wknd-2
          
