name: v3 Sync Tenant Repo to Main Repo
 
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - cores: 4
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # 
      - name: Build and analyze
        env:
          SONAR_TOKEN: "63a6b34b9943b07703025bae65c0952ba09ce8e6"
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=swa-devops_aem-wknd-2
          
