name: v3 Sync Tenant Repo to Main Repo
 
on:
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v17.0.2
      - name: Build and analyze
        env:
          SONAR_TOKEN: "63a6b34b9943b07703025bae65c0952ba09ce8e6"
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=swa-devops_aem-wknd-2
          
